/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WirdRouteImport } from './routes/wird'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PairReviewRouteImport } from './routes/pair-review'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as IndexRouteImport } from './routes/index'

const WirdRoute = WirdRouteImport.update({
  id: '/wird',
  path: '/wird',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PairReviewRoute = PairReviewRouteImport.update({
  id: '/pair-review',
  path: '/pair-review',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/notifications': typeof NotificationsRoute
  '/pair-review': typeof PairReviewRoute
  '/report': typeof ReportRoute
  '/session': typeof SessionRoute
  '/wird': typeof WirdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/notifications': typeof NotificationsRoute
  '/pair-review': typeof PairReviewRoute
  '/report': typeof ReportRoute
  '/session': typeof SessionRoute
  '/wird': typeof WirdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups': typeof GroupsRoute
  '/notifications': typeof NotificationsRoute
  '/pair-review': typeof PairReviewRoute
  '/report': typeof ReportRoute
  '/session': typeof SessionRoute
  '/wird': typeof WirdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups'
    | '/notifications'
    | '/pair-review'
    | '/report'
    | '/session'
    | '/wird'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups'
    | '/notifications'
    | '/pair-review'
    | '/report'
    | '/session'
    | '/wird'
  id:
    | '__root__'
    | '/'
    | '/groups'
    | '/notifications'
    | '/pair-review'
    | '/report'
    | '/session'
    | '/wird'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsRoute: typeof GroupsRoute
  NotificationsRoute: typeof NotificationsRoute
  PairReviewRoute: typeof PairReviewRoute
  ReportRoute: typeof ReportRoute
  SessionRoute: typeof SessionRoute
  WirdRoute: typeof WirdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wird': {
      id: '/wird'
      path: '/wird'
      fullPath: '/wird'
      preLoaderRoute: typeof WirdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-review': {
      id: '/pair-review'
      path: '/pair-review'
      fullPath: '/pair-review'
      preLoaderRoute: typeof PairReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsRoute: GroupsRoute,
  NotificationsRoute: NotificationsRoute,
  PairReviewRoute: PairReviewRoute,
  ReportRoute: ReportRoute,
  SessionRoute: SessionRoute,
  WirdRoute: WirdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
